# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nardwuar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nardwuar
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'NardwuarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
